name: Export to Notion workspace

on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 5 * * *' # run at 5.30 AM daily

permissions:
  contents: write
  pull-requests: write

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_ROOT_PAGE: ${{ inputs.NOTION_ROOT_PAGE || vars.NOTION_ROOT_PAGE }}

jobs:
  export-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/export-notion/requirements.txt
      - name: Export to Notion
        run: |
          python scripts/export-notion/main.py .
