name: Refresh Context7

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */10 * *' # run every 10 days

jobs:
  refresh-context7:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh doc
        run: |
          curl 'https://context7.com/api/refresh-library' \
            -H 'content-type: application/json' \
            --data-raw '{"libraryName":"/blaxel-ai/docs"}'
